### ISSUE TITLE
"leak"

### ISSUE THREAD

**Issue by GAGOU78** [Its-Vichy/Selfbot-Leak#2]
tu les leak pas comme ils sont déjà open source

**Comment by GAGOU78** [comment]
et ils sont open source et pas obfusquer

**Comment by Its-Vichy** [comment]
Me casse pas les couilles,
Avant de venir commenter, regarde les pull-requests. Ce n'est pas moi qui ai poster les sources,

**Comment by GAGOU78** [comment]
...
